# Generated by Django 3.0.8 on 2020-07-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proton', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='question',
            new_name='project',
        ),
    ]
